### PR TITLE
Migrate to pygit2

### LINKED ISSUE #24: rewrite git-to-freshports-xml.py using devel/py-pygit2
re https://github.com/FreshPorts/git_proc_commit/blob/master/git-to-freshports/git-to-freshports-xml.py

I'm getting feedback from bapt and manu that [devel/py-pygit2](https://www.freshports.org/devel/py-pygit2/) is the python interface of libgit2 and we would be better off using that library.  See https://www.pygit2.org

see also https://github.com/iterative/dvc/issues/2215

Is anyone available to do this rewrite please?

### PR DESCRIPTION
**Pull request by skozlov404**
fixes #24

### CODE REVIEW

**Comment by dlangille** [comment]
I copied the new script to `git-to-freshports-xml-new.py`

I took `git-single-commit.sh` and modified it to invoke both scripts, with different output directories.

```
 where we do dump the XML files which we create?
XML="${INGRESS_MSGDIR}/testing"

logfile "repo is $REPODIR"
logfile "XML dir is $XML"

cd ${REPODIR}

logfile "${SCRIPTDIR}/git-to-freshports-xml.py --repo ${repo} --path ${REPODIR} --commit ${commit_hash} --spooling ${INGRESS_SPOOLINGDIR} --output ${XML}"
         ${SCRIPTDIR}/git-to-freshports-xml.py --repo ${repo} --path ${REPODIR} --commit ${commit_hash} --spooling ${INGRESS_SPOOLINGDIR} --output ${XML}

XML="${INGRESS_MSGDIR}/testing-new"

logfile "${SCRIPTDIR}/git-to-freshports-xml-new.py --repo ${repo} --path ${REPODIR} --commit ${commit_hash} --spooling ${INGRESS_SPOOLINGDIR} --output ${XML}"
         ${SCRIPTDIR}/git-to-freshports-xml-new.py --repo ${repo} --path ${REPODIR} --commit ${commit_hash} --spooling ${INGRESS_SPOOLINGDIR} --output ${XML}

${LOGGER} -t ${LOGGERTAG} ending
logfile "ending"
```

I saw a difference in `HashShort`, with `pygit2` including a longer short-hash in 67 of 94 XML files.  I do not see this as a problem.

I am looking at other issues next.

**Comment by dlangille** [comment]
Looking at ec92d46127fcffd0cfce1b2146515442fcfcac6b:

* Github commit: https://github.com/freebsd/freebsd-ports/commit/ec92d46
* FreshPorts production commit: https://www.freshports.org/commit.php?category=editors&port=nvi2-port&files=yes&message_id=202007270130.06R1UdBj096253@repo.freebsd.org

This was the creation of a new port.  It was supposed to be: `editors/nvi2` but was added in error as `editors/nvi2-port`

Here is part of the original git XML created by `git-to-freshports-xml.py`:

```
    <FILES>
      <FILE Action="Modify" Path="editors/Makefile"/>
      <FILE Action="Add" Path="editors/nvi2-port/Makefile"/>
      <FILE Action="Add" Path="editors/nvi2-port/distinfo"/>
      <FILE Action="Add" Path="editors/nvi2-port/pkg-descr"/>
    </FILES>
```

FYI, the original script still produces the same output:

```
[ingress@devgit-ingress01 ~/message-queues]$ diff -ruN  testing/2020.07.27.01.30.39.000076.ec92d46127fcffd0cfce1b2146515442fcfcac6b.xml ~freshports/message-queues/recent/2020.07.27.01.30.39.000000.ec92d46127fcffd0cfce1b2146515442fcfcac6b.xml
[ingress@devgit-ingress01 ~/message-queues]$ 
```

The `pygit2` XML is:

```
      <FILE Action="Modify" Path="editors/Makefile"/>
      <FILE Action="Delete" Path="editors/nvi2-port/Makefile"/>
      <FILE Action="Delete" Path="editors/nvi2-port/distinfo"/>
      <FILE Action="Delete" Path="editors/nvi2-port/pkg-descr"/>
```

**Comment by dlangille** [comment]
This is the full diff of the test:

[diffs.txt](https://github.com/FreshPorts/git_proc_commit/files/4982519/diffs.txt)

**Comment by dlangille** [comment]
Looking at 7ce4a78379b30fd44b5db86e0e1cce0bf410936d (https://github.com/freebsd/freebsd-ports/commit/7ce4a7)

New xml is:

```
    <FILES>
      <FILE Action="Modify" Path="security/softether-devel/Makefile"/>
      <FILE Action="Delete" Path="security/softether-devel/files/patch-increase-nat-sessions"/>
      <FILE Action="Modify" Path="security/softether/Makefile"/>
      <FILE Action="Delete" Path="security/softether/files/patch-increase-nat-sessions"/>
    </FILES>
```

Old XML is:

```
      <FILE Action="Modify" Path="security/softether-devel/Makefile"/>
      <FILE Action="Add" Path="security/softether-devel/files/patch-increase-nat-sessions"/>
      <FILE Action="Modify" Path="security/softether/Makefile"/>
      <FILE Action="Add" Path="security/softether/files/patch-increase-nat-sessions"/>
```

Some Adds are coming through as Deletes. I am not sure why yet.

**Comment by dlangille** [comment]
I think this is the fix:

-         for diff_delta in repo.diff(commit, commit.parents[0]).deltas:
+        for diff_delta in repo.diff(commit.parents[0], commit).deltas:

That is, I think the diff needs to be reversed.

**Comment by dlangille** [comment]
Ignoring the short-hash length, which I do not consider an issue, the remaining differences are in renames.

`git` - does a rename
`pygit2` - seems to do a delete and add

```
diff -ruN testing/2020.07.27.01.58.33.000078.fd2bb768b5a39d29758b8f74bc15c321d6b4f980.xml testing-new/2020.07.27.01.58.33.000078.fd2bb768b5a39d29758b8f74bc15c321d6b4f980.xml
--- testing/2020.07.27.01.58.33.000078.fd2bb768b5a39d29758b8f74bc15c321d6b4f980.xml     2020-07-27 18:33:33.356524000 +0000
+++ testing-new/2020.07.27.01.58.33.000078.fd2bb768b5a39d29758b8f74bc15c321d6b4f980.xml 2020-07-27 18:33:49.647481000 +0000
@@ -10,12 +10,15 @@
     <PEOPLE>
       <UPDATER Handle="leres &lt;leres@FreeBSD.org&gt;"/>
     </PEOPLE>
-    <COMMIT Hash="fd2bb768b5a39d29758b8f74bc15c321d6b4f980" HashShort="fd2bb7" Subject="editors/nvi2-port: Rename to editors/nvi2" EncodingLoses="false" Repository="ports"/>
+    <COMMIT Hash="fd2bb768b5a39d29758b8f74bc15c321d6b4f980" HashShort="fd2bb76" Subject="editors/nvi2-port: Rename to editors/nvi2" EncodingLoses="false" Repository="ports"/>
     <FILES>
       <FILE Action="Modify" Path="editors/Makefile"/>
-      <FILE Action="Rename" Path="editors/nvi2-port/Makefile" Destination="editors/nvi2/Makefile"/>
-      <FILE Action="Rename" Path="editors/nvi2-port/distinfo" Destination="editors/nvi2/distinfo"/>
-      <FILE Action="Rename" Path="editors/nvi2-port/pkg-descr" Destination="editors/nvi2/pkg-descr"/>
+      <FILE Action="Delete" Path="editors/nvi2-port/Makefile"/>
+      <FILE Action="Delete" Path="editors/nvi2-port/distinfo"/>
+      <FILE Action="Delete" Path="editors/nvi2-port/pkg-descr"/>
+      <FILE Action="Add" Path="editors/nvi2/Makefile"/>
+      <FILE Action="Add" Path="editors/nvi2/distinfo"/>
+      <FILE Action="Add" Path="editors/nvi2/pkg-descr"/>
     </FILES>
   </UPDATE>
 </UPDATES>

```

```
diff -ruN testing/2020.07.26.08.01.07.000020.d5c503dd5c31a156c7cc5b78afbf98cb2643d716.xml testing-new/2020.07.26.08.01.07.000020.d5c503dd5c31a156c7cc5b78afbf98cb2643d716.xml
--- testing/2020.07.26.08.01.07.000020.d5c503dd5c31a156c7cc5b78afbf98cb2643d716.xml     2020-07-27 18:33:28.892544000 +0000
+++ testing-new/2020.07.26.08.01.07.000020.d5c503dd5c31a156c7cc5b78afbf98cb2643d716.xml 2020-07-27 18:33:40.041354000 +0000
@@ -8,11 +8,12 @@
     <PEOPLE>
       <UPDATER Handle="demon &lt;demon@FreeBSD.org&gt;"/>
     </PEOPLE>
-    <COMMIT Hash="d5c503dd5c31a156c7cc5b78afbf98cb2643d716" HashShort="d5c503" Subject="Update to version 2.2.1." EncodingLoses="false" Repository="ports"/>
+    <COMMIT Hash="d5c503dd5c31a156c7cc5b78afbf98cb2643d716" HashShort="d5c503d" Subject="Update to version 2.2.1." EncodingLoses="false" Repository="ports"/>
     <FILES>
       <FILE Action="Modify" Path="net/haproxy/Makefile"/>
       <FILE Action="Modify" Path="net/haproxy/distinfo"/>
-      <FILE Action="Rename" Path="net/haproxy/files/patch-include-common-hathreads.h" Destination="net/haproxy/files/patch-include-haproxy-atomic.h"/>
+      <FILE Action="Delete" Path="net/haproxy/files/patch-include-common-hathreads.h"/>
+      <FILE Action="Add" Path="net/haproxy/files/patch-include-haproxy-atomic.h"/>
       <FILE Action="Modify" Path="net/haproxy/pkg-plist"/>
     </FILES>
   </UPDATE>
```

**Comment by skozlov404** [comment]
- I've changed the order of commits, so it now should diff as expected
- HashShort should be longer by git standards, the previous version had a bug, so I'd leave it longer if possible
- I'm still looking into the rename issue

**Comment by skozlov404** [comment]
Seems like the rename issue us now resolved. Could you please check it one more time?
In the meantime I think I'll write some more tests for rename etc.

**Comment by dlangille** [comment]
Recent testing indicates the only differences are `HashShort`, which we have agreed is fine.

**Comment by dlangille** [comment]
> Seems like the rename issue us now resolved. Could you please check it one more time?
> In the meantime I think I'll write some more tests for rename etc.

Now, I am not sure if I prefer Rename or Delete & Add.  I have to think and test some more.  I had a long [twitter thread](https://twitter.com/DLangille/status/1287861346801987585) about this last night.

I see the new line which controls this:

```
diff.find_similar()  # Look for renames
```

Thank you.

**Comment by dlangille** [comment]
Relevant blog posts:

* https://news.freshports.org/2020/07/29/git-changing-libraries-gave-us-new-xml-options/
* https://news.freshports.org/2020/07/30/for-git-commits-which-is-better-rename-a-to-b-or-delete-a-add-b/

FYI, I think `delete` & `add` is better than `rename`.

**Pull request merged**
