### PR TITLE
Add git-to-freshports script

### PR DESCRIPTION
**Pull request by skozlov404**
Event:		EuroBSDCon 2019 Hackathon
Sponsored by:	Intel Corporation

### CODE REVIEW

**Comment by dlangille** [comment]
Thank you for your work on this. I hope to test it soon.

**Comment by dlangille** [comment]
This worked on my laptop. Thank you.

**Comment by skozlov404** [comment]
Great news, thanks for letting me know. If you find any bugs please notify
me, I'll try to fix it.

Sergey

**Comment by dlangille** [comment]
I started working on processing the XML.

Please include the hash into the XML. I know it is in the filename, but we should also put it into the XML.

I would also like repo name in there.  Just hardcode it to ports for now please.

**Comment by dlangille** [comment]
We have the first commit loaded into the database.  Further processing is required, but I managed to get this hacking done on the train from Lillehammer to Oslo airport.

```
freshports=# select id, message_id, committer, description  from commit_log order by id desc limit 2;
   id   |                  message_id                  | committer |                                 description                                  
--------+----------------------------------------------+-----------+------------------------------------------------------------------------------
 766918 | f2bfe60090b840b6d99a3288c0b745843cefcfe1     | feld      | net-mgmt/unifi5: Update to 5.11.46                                          +
        |                                              |           |                                                                             +
        |                                              |           | Also pull in port improvements from glewis@ to enable customizing which Java+
        |                                              |           | that Unifi runs with                                                        +
        |                                              |           |                                                                             +
        |                                              |           | PR:             240016
 766908 | 201909201136.x8KBaUna058053@repo.freebsd.org | jhale     | Update security/*gpgme* to 1.13.1
(2 rows)

freshports=# 

```

**Comment by jpmens** [comment]
@dlangille you shouldn't have to say put "this element" between "that and that"; XML is agnostic to that as the proper parsers won't care. On the contrary: it typically isn't possible to define how the elements/tags are output. :-)

**Comment by dlangille** [comment]
Agreed. 

The placement is for humans reading it when debugging. We are writing a file. We can control the placement.

**Comment by skozlov404** [comment]
> I would also like repo name in there. Just hardcode it to ports for now please.

It's already there, in the OS section. It defaults to 'ports', but you can change is by using cmdline flags to the script. In the next pull request it's also used in the COMMIT tag #2 

> EDIT: after working on the code more: It looks like we should add a COMMIT clause, where we once had MESSAGE:
> 
> ```
>         <COMMIT Hash="f2bfe60090b840b6d99a3288c0b745843cefcfe1" EncodingLosses="false" Repository="ports"/>
> ```
> 
> Let's put it between PEOPLE and FILES.

Done in the next pull request #2 I wasn't sure what EncodingLosses have to be, so just hard-coded it for now.

**Comment by skozlov404** [comment]
> @dlangille you shouldn't have to say put "this element" between "that and that"; XML is agnostic to that as the proper parsers won't care. On the contrary: it typically isn't possible to define how the elements/tags are output. :-)

The parser I'm using preserves order, although it's not strictly enforced by the XML standard. I believe most of parsers/emitters preserve order because it's important in HTML.

**Comment by dlangille** [comment]
See https://news.freshports.org/2020/06/21/git-the-next-freshports-project/

**Pull request merged**
